# Generated by Django 5.1.4 on 2024-12-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_options_todo_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
